import { Invoice } from "./types";

export const initialInvoices: Invoice[] = [
  {
    id: "inv-costco",
    invoiceNumber: "CS-928104",
    supplierName: "Costco Wholesale",
    date: "2026-07-02",
    totalAmount: 1144.92,
    currency: "USD",
    objectName: "Main Office",
    createdAt: "2026-07-02T10:00:00.000Z",
    invoiceType: "expense",
    items: [
      {
        id: "item-costco-1",
        description: "Dell 27\" Monitor S2721QS",
        type: "goods",
        quantity: 2,
        unitPrice: 299.99,
        totalPrice: 599.98,
        expenseCategory: "materials",
      },
      {
        id: "item-costco-2",
        description: "HP LaserJet Pro MFP M227fdw",
        type: "goods",
        quantity: 1,
        unitPrice: 329.99,
        totalPrice: 329.99,
        expenseCategory: "office_expenses",
      },
      {
        id: "item-costco-3",
        description: "Kirkland Signature Copy Paper (10 reams)",
        type: "goods",
        quantity: 5,
        unitPrice: 42.99,
        totalPrice: 214.95,
        expenseCategory: "office_expenses",
      },
    ],
  },
  {
    id: "inv-marshalls",
    invoiceNumber: "MR-482910",
    supplierName: "Marshalls",
    date: "2026-07-05",
    totalAmount: 619.87,
    currency: "USD",
    objectName: "Interior Decor",
    createdAt: "2026-07-05T12:30:00.000Z",
    invoiceType: "expense",
    items: [
      {
        id: "item-marshalls-1",
        description: "Ergonomic Office Chair Mesh",
        type: "goods",
        quantity: 3,
        unitPrice: 129.99,
        totalPrice: 389.97,
        expenseCategory: "office_expenses",
      },
      {
        id: "item-marshalls-2",
        description: "Leather Desk Pad Protector",
        type: "goods",
        quantity: 4,
        unitPrice: 19.99,
        totalPrice: 79.96,
        expenseCategory: "office_expenses",
      },
      {
        id: "item-marshalls-3",
        description: "LED Desk Lamp with USB Charger",
        type: "goods",
        quantity: 6,
        unitPrice: 24.99,
        totalPrice: 149.94,
        expenseCategory: "office_expenses",
      },
    ],
  },
  {
    id: "inv-homedepot",
    invoiceNumber: "HD-8849201",
    supplierName: "The Home Depot",
    date: "2026-06-28",
    totalAmount: 721.46,
    currency: "USD",
    objectName: "Site A",
    createdAt: "2026-06-28T09:15:00.000Z",
    invoiceType: "expense",
    items: [
      {
        id: "item-homedepot-1",
        description: "DeWalt 20V Max Cordless Drill Kit",
        type: "goods",
        quantity: 2,
        unitPrice: 159.00,
        totalPrice: 318.00,
        expenseCategory: "materials",
      },
      {
        id: "item-homedepot-2",
        description: "Commercial Electric 4ft LED Shop Light",
        type: "goods",
        quantity: 10,
        unitPrice: 29.97,
        totalPrice: 299.70,
        expenseCategory: "materials",
      },
      {
        id: "item-homedepot-3",
        description: "Philips LED Warm White Bulbs (4-pack)",
        type: "goods",
        quantity: 8,
        unitPrice: 12.97,
        totalPrice: 103.76,
        expenseCategory: "materials",
      },
    ],
  },
  {
    id: "inv-amazon",
    invoiceNumber: "AMZ-9920184",
    supplierName: "Amazon Business",
    date: "2026-07-08",
    totalAmount: 1199.87,
    currency: "USD",
    objectName: "IT Infrastructure",
    createdAt: "2026-07-08T15:00:00.000Z",
    invoiceType: "expense",
    items: [
      {
        id: "item-amazon-1",
        description: "Logitech MX Master 3S Wireless Mouse",
        type: "goods",
        quantity: 5,
        unitPrice: 99.99,
        totalPrice: 499.95,
        expenseCategory: "office_expenses",
      },
      {
        id: "item-amazon-2",
        description: "Logitech MX Keys S Wireless Keyboard",
        type: "goods",
        quantity: 5,
        unitPrice: 109.99,
        totalPrice: 549.95,
        expenseCategory: "office_expenses",
      },
      {
        id: "item-amazon-3",
        description: "Anker USB-C Multi-Port Hub (8-in-1)",
        type: "goods",
        quantity: 3,
        unitPrice: 49.99,
        totalPrice: 149.97,
        expenseCategory: "office_expenses",
      },
    ],
  },
  // --- INCOMES ---
  {
    id: "inv-income-1",
    invoiceNumber: "INC-2026-001",
    supplierName: "Acme Client Corp",
    date: "2026-06-20",
    totalAmount: 4500.00,
    currency: "USD",
    objectName: "Consulting",
    createdAt: "2026-06-20T11:00:00.000Z",
    invoiceType: "income",
    items: [
      {
        id: "item-income-1-1",
        description: "Software Architecture Consulting - Phase 1",
        type: "service",
        quantity: 1,
        unitPrice: 4500.00,
        totalPrice: 4500.00,
        expenseCategory: "other",
      }
    ]
  },
  {
    id: "inv-income-2",
    invoiceNumber: "INC-2026-002",
    supplierName: "Global Brands Corp",
    date: "2026-07-02",
    totalAmount: 4000.00,
    currency: "USD",
    objectName: "Marketing Services",
    createdAt: "2026-07-02T15:00:00.000Z",
    invoiceType: "income",
    items: [
      {
        id: "item-income-2-1",
        description: "Milestone payment for Brand Guidelines Delivery",
        type: "service",
        quantity: 1,
        unitPrice: 4000.00,
        totalPrice: 4000.00,
        expenseCategory: "other",
      }
    ]
  },
  {
    id: "inv-income-3",
    invoiceNumber: "INC-2026-003",
    supplierName: "Partner Tech Corp",
    date: "2026-07-11",
    totalAmount: 850.00,
    currency: "USD",
    objectName: "Technical Support",
    createdAt: "2026-07-11T10:30:00.000Z",
    invoiceType: "income",
    items: [
      {
        id: "item-income-3-1",
        description: "Website Maintenance & Support Services",
        type: "service",
        quantity: 1,
        unitPrice: 850.00,
        totalPrice: 850.00,
        expenseCategory: "other",
      }
    ]
  }
];
